FROM ubuntu:18.04
LABEL maintainer="sohiljain"

# Never prompts the user for choices on installation/configuration of packages
ENV DEBIAN_FRONTEND noninteractive
ENV TERM linux

# Airflow
ARG AIRFLOW_VERSION=1.10.2
ARG AIRFLOW_HOME=/usr/local/airflow
ARG AIRFLOW_DEPS=""
ARG PYTHON_DEPS=""
ENV AIRFLOW_GPL_UNIDECODE yes

# Define en_US.
ENV LANGUAGE en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LC_ALL en_US.UTF-8
ENV LC_CTYPE en_US.UTF-8
ENV LC_MESSAGES en_US.UTF-8

RUN set -ex \
&& myapps='curl git htop man unzip vim wget telnetd apt-utils locate netcat locales logrotate monit sudo ssh lsof' \
&& buildDeps='freetds-dev libkrb5-dev libsasl2-dev libssl-dev libffi-dev libpq-dev' \
&& apt update -yqq \
&& apt-get install -yqq --no-install-recommends software-properties-common \
&& echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | debconf-set-selections \
&& add-apt-repository -y ppa:webupd8team/java \
&& add-apt-repository -y ppa:deadsnakes/ppa \
&& apt-get update -yqq \
&& apt-get upgrade -yqq \
&& apt-get install -yqq --no-install-recommends \
    $myapps \
    $buildDeps \
    freetds-bin \
    build-essential \
    default-libmysqlclient-dev \
    python3 python3-pip python3-dev python3-virtualenv libpq-dev \
    rsync \
    netcat \
    locales \
&& sed -i 's/^# en_US.UTF-8 UTF-8$/en_US.UTF-8 UTF-8/g' /etc/locale.gen \
&& locale-gen \
&& update-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 \
&& useradd -ms /bin/bash -d ${AIRFLOW_HOME} -p airflow airflow \
&& pip3 install -U pip setuptools wheel \
&& pip3.6 install pytz \
&& pip3.6 install pyOpenSSL \
&& pip3.6 install ndg-httpsclient \
&& pip3.6 install pyasn1 \
&& pip3.6 install awscli --upgrade --user \
&& pip3.6 install 'redis>=2.10.5,<3' \
&& if [ -n "${PYTHON_DEPS}" ]; then pip install ${PYTHON_DEPS}; fi

RUN pip3.6 install apache-airflow[crypto,celery,postgres,hive,jdbc,mysql,s3,rabbitmq,slack,google_auth,password,ssh${AIRFLOW_DEPS:+,}${AIRFLOW_DEPS}]==${AIRFLOW_VERSION}

COPY script/entrypoint.sh /entrypoint.sh
COPY config/airflow.cfg ${AIRFLOW_HOME}/airflow.cfg

RUN chown -R airflow: ${AIRFLOW_HOME}

EXPOSE 8080 5555 8793

#USER airflow
RUN alias python=$(which python3)

WORKDIR ${AIRFLOW_HOME}
#ENTRYPOINT ["/entrypoint.sh"]
#CMD ["bash"] # set default arg for entrypoint
